USE TENNIS;

-- Allows you to run updates and deletes
set sql_safe_updates = 0;

select * from players

SELECT   PLAYERNO, NAME, BIRTH_DATE
FROM     PLAYERS
WHERE    TOWN = 'Stratford'
ORDER BY 1;




SELECT   PLAYERNO, NAME, BIRTH_DATE
FROM     PLAYERS
WHERE    JOINED > 1980
OR      TOWN = 'Stratford'
ORDER BY PLAYERNO;


UPDATE   PENALTIES
SET      AMOUNT = 200
WHERE    PLAYERNO = 8
;

SELECT   PLAYERNO, AMOUNT
FROM     PENALTIES
WHERE    PLAYERNO = 44;




DELETE
FROM     PENALTIES
WHERE    AMOUNT > 100;



SELECT   MATCHNO, WON - LOST RESULT
FROM     MATCHES
WHERE    WON = LOST + 2;




SELECT   PAYMENTNO, AMOUNT * 100 AS CENTS
FROM     PENALTIES;


SELECT   MATCHNO AS PRIMKEY,
         80 AS EIGHTY,
         WON - LOST AS DIFFERENCE,
         TIME('23:59:59') AS ALMOST_MIDNIGHT,
         'TEXT' AS TEXT
FROM     MATCHES
WHERE    MATCHNO <= 4;




SELECT   PAYMENTNO, AMOUNT * 100 AS CENTS
FROM     PENALTIES
ORDER BY CENTS;


SET @PLAYERNO = 7;


SELECT   NAME, TOWN, POSTCODE
FROM     PLAYERS
WHERE    PLAYERNO < @PLAYERNO;



SELECT   *
FROM     PENALTIES
WHERE    PAYMENT_DATE = CURRENT_DATE;


SELECT   PLAYERNO, TOWN, BIRTH_DATE, 
         CASE TOWN 
            WHEN 'Stratford' THEN 0
            WHEN 'Plymouth'  THEN 1
            WHEN 'Inglewood' THEN 2
            ELSE 3 
         END AS P,
         CASE TOWN 
            WHEN 'Stratford' THEN 
               CASE BIRTH_DATE 
                  WHEN '1948-09-01' THEN 'Old Stratforder'
                  ELSE 'Young Stratforder' END
            WHEN 'Inglewood' THEN
               CASE BIRTH_DATE
                  WHEN '1962-07-08' THEN 'Old Inglewooder'
                  ELSE 'Young Inglewooder' END
            ELSE 'Rest' 
         END AS TYPE
FROM     PLAYERS;


SELECT   PAYMENTNO, YEAR(PAYMENT_DATE)
FROM     PENALTIES
WHERE    YEAR(PAYMENT_DATE) > 1980;


SELECT   PLAYERNO,
         CONCAT(CONCAT(LEFT(INITIALS, 1), '. '), NAME) 
         AS FULL_NAME
FROM     PLAYERS
WHERE    LEFT(NAME, 1) = 'B';


SELECT   INITIALS, NAME, COALESCE(LEAGUENO, 1)
FROM     PLAYERS
WHERE    Town = 'Stratford';

SELECT COALESCE(LEAGUENO,'NO LEAGUE NUMBER') AS LEAGUE_NO  FROM PLAYERS;


SELECT   PLAYERNO, DAYNAME(BIRTH_DATE),
        MONTHNAME(BIRTH_DATE), DAYOFYEAR(BIRTH_DATE)
FROM     PLAYERS
WHERE    PLAYERNO < 10;


SELECT   PLAYERNO, BEGIN_DATE, END_DATE, 
         DATEDIFF(END_DATE, BEGIN_DATE)
FROM     COMMITTEE_MEMBERS
WHERE    DATEDIFF(END_DATE, BEGIN_DATE) > 500
OR      (END_DATE IS NULL AND 
         DATEDIFF(CURRENT_DATE, BEGIN_DATE) > 500)
ORDER BY PLAYERNO

;


SELECT   CONCAT(RTRIM(NAME), CAST(BIRTH_DATE AS CHAR(10)))
FROM     PLAYERS
WHERE    TOWN = 'Inglewood'
;

SELECT   PLAYERNO, TOWN || ' ' || STREET || ' ' || HOUSENO
FROM     PLAYERS
WHERE    TOWN = 'Stratford'
;

SELECT   PAYMENTNO, PAYMENT_DATE
FROM     PENALTIES
WHERE    PAYMENT_DATE >= '1982-12-25'
AND      PAYMENT_DATE <= '1982-12-25' + INTERVAL 6 DAY;




SELECT   PLAYERNO
FROM     PLAYERS
WHERE    DAYNAME(BIRTH_DATE) = 
        (SELECT   DAYNAME(BIRTH_DATE)
         FROM     PLAYERS
         WHERE    PLAYERNO = 2);
         
         
         
use sample;
 
         
   SELECT EMPNO, SALARY
   FROM employee
   WHERE SALARY > (SELECT AVG(SALARY) FROM employee);

USE TENNIS;

SELECT   PLAYERNO
FROM     COMMITTEE_MEMBERS
WHERE   (BEGIN_DATE, END_DATE) =
        (SELECT   BEGIN_DATE, END_DATE
         FROM     COMMITTEE_MEMBERS
         WHERE    PLAYERNO = 8
         AND      POSITION = 'Treasurer')
AND      PLAYERNO <> 8;



SELECT   PL.PLAYERNO, NAME, AMOUNT
FROM     PLAYERS AS PL, PENALTIES AS PN
WHERE    PL.PLAYERNO = PN.PLAYERNO
AND      BIRTH_DATE > '1920-06-30';



SELECT   TEAMNO, NAME
FROM     TEAMS INNER JOIN PLAYERS
         ON TEAMS.PLAYERNO = PLAYERS.PLAYERNO

;
SELECT * FROM PLAYERS

SELECT   PAYMENTNO, NAME, PLAYERS.PLAYERNO
FROM     PENALTIES LEFT OUTER JOIN PLAYERS
         ON PENALTIES.PLAYERNO = PLAYERS.PLAYERNO
ORDER BY 1;





SELECT   P.PLAYERNO, NAME, TEAMNO, DIVISION
FROM     PLAYERS AS P LEFT OUTER JOIN TEAMS AS T
         ON P.PLAYERNO = T.PLAYERNO
ORDER BY P.PLAYERNO;




SELECT   PLAYERS.PLAYERNO, NAME, AMOUNT, TEAMNO
FROM     PLAYERS LEFT OUTER JOIN PENALTIES
         ON PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
            LEFT OUTER JOIN MATCHES
            ON PLAYERS.PLAYERNO = MATCHES.PLAYERNO
WHERE    TOWN = 'Inglewood';


SELECT   PLAYERS.PLAYERNO, NAME, TEAMNO
FROM     TEAMS RIGHT OUTER JOIN PLAYERS
         ON TEAMS.PLAYERNO = PLAYERS.PLAYERNO;